[package]
name = "post"
version = "0.0.0"
authors = ["Tshepang Lekhonkhobe <tshepang@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "4"
chrono = "0.4"
slug = "0.1"

[dependencies.clap]
version = "3"
features = [ "derive" ]
